// Package ids is the shared kernel: identifier types used across bounded
// contexts. It deliberately contains nothing but the types themselves.
// Identifiers are generated by use cases (through an IDGenerator port),
// never here and never inside a domain package.
package ids

import (
	"fmt"

	"github.com/google/uuid"
)

// SessionID is the public identifier of an anonymous session.
// It is visible to other users; the secret session token is a different value.
type SessionID uuid.UUID

// ParseSessionID parses the canonical textual form of a SessionID.
func ParseSessionID(s string) (SessionID, error) {
	u, err := uuid.Parse(s)
	if err != nil {
		return SessionID{}, fmt.Errorf("parse session id: %w", err)
	}
	return SessionID(u), nil
}

func (id SessionID) String() string  { return uuid.UUID(id).String() }
func (id SessionID) IsZero() bool    { return id == SessionID{} }
func (id SessionID) UUID() uuid.UUID { return uuid.UUID(id) }

// MarshalText renders the canonical textual form, so encoding/json and
// log/slog render a SessionID as a string instead of a raw byte array.
func (id SessionID) MarshalText() ([]byte, error) {
	return []byte(id.String()), nil
}

// UnmarshalText parses the canonical textual form.
func (id *SessionID) UnmarshalText(text []byte) error {
	parsed, err := ParseSessionID(string(text))
	if err != nil {
		return err
	}
	*id = parsed
	return nil
}

// RoomID identifies a room. Users address rooms by hash; RoomID is internal.
type RoomID uuid.UUID

// ParseRoomID parses the canonical textual form of a RoomID.
func ParseRoomID(s string) (RoomID, error) {
	u, err := uuid.Parse(s)
	if err != nil {
		return RoomID{}, fmt.Errorf("parse room id: %w", err)
	}
	return RoomID(u), nil
}

func (id RoomID) String() string  { return uuid.UUID(id).String() }
func (id RoomID) IsZero() bool    { return id == RoomID{} }
func (id RoomID) UUID() uuid.UUID { return uuid.UUID(id) }

// MarshalText renders the canonical textual form, so encoding/json and
// log/slog render a RoomID as a string instead of a raw byte array.
func (id RoomID) MarshalText() ([]byte, error) {
	return []byte(id.String()), nil
}

// UnmarshalText parses the canonical textual form.
func (id *RoomID) UnmarshalText(text []byte) error {
	parsed, err := ParseRoomID(string(text))
	if err != nil {
		return err
	}
	*id = parsed
	return nil
}

// MessageID identifies a message. It is a UUIDv7, so it sorts by creation
// time and doubles as the pagination cursor.
type MessageID uuid.UUID

// ParseMessageID parses the canonical textual form of a MessageID.
func ParseMessageID(s string) (MessageID, error) {
	u, err := uuid.Parse(s)
	if err != nil {
		return MessageID{}, fmt.Errorf("parse message id: %w", err)
	}
	return MessageID(u), nil
}

func (id MessageID) String() string  { return uuid.UUID(id).String() }
func (id MessageID) IsZero() bool    { return id == MessageID{} }
func (id MessageID) UUID() uuid.UUID { return uuid.UUID(id) }

// MarshalText renders the canonical textual form, so encoding/json and
// log/slog render a MessageID as a string instead of a raw byte array.
func (id MessageID) MarshalText() ([]byte, error) {
	return []byte(id.String()), nil
}

// UnmarshalText parses the canonical textual form.
func (id *MessageID) UnmarshalText(text []byte) error {
	parsed, err := ParseMessageID(string(text))
	if err != nil {
		return err
	}
	*id = parsed
	return nil
}
